version: '3.3'
services:    
    srv_persistor:
        build: 
            context: ./
            
            dockerfile: ./srv_persistor/Dockerfile
        ports:
            - "50051:50051"
    srv_reader:
        build: 
            context: ./
            dockerfile: ./srv_reader/Dockerfile
        environment:
            - DIR_FILE=/tmp/data/10000_sr.csv
        depends_on: 
            - srv_persistor
