# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sales_records.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13sales_records.proto\"\x0e\n\x0c\x45mptyMessage\"\'\n\x18PingSalesRecordsResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t\"\x83\x01\n\x13SalesRecordsRequest\x12\x0e\n\x06region\x18\x01 \x01(\t\x12\x11\n\titem_type\x18\x02 \x01(\t\x12\x12\n\nunits_sold\x18\x03 \x01(\t\x12\x12\n\nunit_price\x18\x04 \x01(\t\x12\x11\n\tunit_cost\x18\x05 \x01(\t\x12\x0e\n\x06source\x18\x06 \x01(\t\"#\n\x13SalesRecordsRespose\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2\x89\x01\n\x0bSalesRecord\x12;\n\x0fPingSalesRecord\x12\r.EmptyMessage\x1a\x19.PingSalesRecordsResponse\x12=\n\x0fSendSalesRecord\x12\x14.SalesRecordsRequest\x1a\x14.SalesRecordsResposeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sales_records_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTYMESSAGE._serialized_start=23
  _EMPTYMESSAGE._serialized_end=37
  _PINGSALESRECORDSRESPONSE._serialized_start=39
  _PINGSALESRECORDSRESPONSE._serialized_end=78
  _SALESRECORDSREQUEST._serialized_start=81
  _SALESRECORDSREQUEST._serialized_end=212
  _SALESRECORDSRESPOSE._serialized_start=214
  _SALESRECORDSRESPOSE._serialized_end=249
  _SALESRECORD._serialized_start=252
  _SALESRECORD._serialized_end=389
# @@protoc_insertion_point(module_scope)
