# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sales_records_pb2 as sales__records__pb2


class SalesRecordStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PingSalesRecord = channel.unary_unary(
                '/SalesRecord/PingSalesRecord',
                request_serializer=sales__records__pb2.EmptyMessage.SerializeToString,
                response_deserializer=sales__records__pb2.PingSalesRecordsResponse.FromString,
                )
        self.SendSalesRecord = channel.unary_unary(
                '/SalesRecord/SendSalesRecord',
                request_serializer=sales__records__pb2.SalesRecordsRequest.SerializeToString,
                response_deserializer=sales__records__pb2.SalesRecordsRespose.FromString,
                )


class SalesRecordServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PingSalesRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendSalesRecord(self, request, context):
        """para validar que funciona
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SalesRecordServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PingSalesRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.PingSalesRecord,
                    request_deserializer=sales__records__pb2.EmptyMessage.FromString,
                    response_serializer=sales__records__pb2.PingSalesRecordsResponse.SerializeToString,
            ),
            'SendSalesRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSalesRecord,
                    request_deserializer=sales__records__pb2.SalesRecordsRequest.FromString,
                    response_serializer=sales__records__pb2.SalesRecordsRespose.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SalesRecord', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SalesRecord(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PingSalesRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SalesRecord/PingSalesRecord',
            sales__records__pb2.EmptyMessage.SerializeToString,
            sales__records__pb2.PingSalesRecordsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendSalesRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SalesRecord/SendSalesRecord',
            sales__records__pb2.SalesRecordsRequest.SerializeToString,
            sales__records__pb2.SalesRecordsRespose.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
